 language: node_js
 node_js:
   - "0.10"
 before_install:
 install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
notifications:
  email:
    - bsayaz@gmail.com
  on_success: always
  on_failure: always